cheese:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    port: 5432
    database: cheese
    username: postgres
    password: 123456

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBbeouNTWp3QF9ugAys
    access-key-secret: bGZ51vmonUobFXvRun5GUPFw37IG35
    bucket-name: vichen
  redis:
    host: localhost
    database: 10
    port: 6379
    password: 123456
